### ISSUE TITLE
Performance might we wonky on some systems

### ISSUE THREAD

**Issue by tajemniktv** [tajemniktv/TajsGraph#11]
Some users reported FPS being "not stable at all" or FPS being "not so good"

**Comment by CTRQuko** [comment]
> Some users reported FPS being "not stable at all" or FPS being "not so good"

I have a good pc and yes there is no stable fps, but we are modifying the game out of spec. I in ultra with a 4090 barely reach 30-60 fps, with the mod enabled and configured.

**Comment by tajemniktv** [comment]
Thanks for the input, I will be pushing an update in literally 5 minutes that could improve performance by a bit. Not sure how it will impact visual quality tho. 
I couldn't find a definite reason for this - I will be looking into this issue more closely. 

Also: I recommend setting Global Illumination Quality to 2 (Medium), it should look just as well but gives a huge performance boost

**Comment by tajemniktv** [comment]
@CTRQuko just pushed it, please try the 0.9.3 version

**Comment by CTRQuko** [comment]
> @CTRQuko just pushed it, please try the 0.9.4 version
> 
> edit: typo, i meant 0.9.4

I will test it and send you the results,

**Comment by CTRQuko** [comment]
New video 
[https://youtu.be/IE440sGYcfs]()

performance is similar

**Comment by tajemniktv** [comment]
Eh, I will look into this more closely when I'm back from uni... 

Thanks for testing!

**Comment by tajemniktv** [comment]
VSM might be a huge performance hogger;
to do:
* optimize vsm
* implement a opt out option via https://github.com/tajemniktv/TajsGraph/issues/8 of vsm

**Comment by tajemniktv** [comment]
eitherway, I tried optimizing some things in the 0.9.3, should be somewhat better. Stuttering is still there tho, will look into that next;

**Comment by DrShadow34** [comment]
Weird thing, I have 60+ fps while looking at my factory, but slight change to the right (dunno, there like, one additional cactus in the frame) and fps drops to 24ish. 
![normal fps](https://i.imgur.com/ffUDLfg.jpeg)
![low fps](https://i.imgur.com/MAeKkVa.jpeg)
Also, there some weird thing with LOD in general. 
![lod thingy](https://i.imgur.com/iYWxW8H.jpeg)
Ignore green texture, that due to vulkan. My problem with low poly LOD of the ground itself. 
Also, I assume there no trees due to your settings? How can I get them back? Tried different LOD settings for foliage, but looks like it won't affect all trees or something.

**Comment by tajemniktv** [comment]
Hm, that's interesting. Many thanks for the report!
I did see that there's an issue with trees but I thought that changing Foliage View Distance to higher distances worked fine... I will open a separate issue (https://github.com/tajemniktv/TajsGraph/issues/21) for this and look into this more closely. I remember I made some changes to Nanite some time ago, and maybe that's when the issue started happening...

Adding an options UI (https://github.com/tajemniktv/TajsGraph/issues/8) will most likely help debug most of the issues (via letting end-users play with settings and *hopefully* them reporting issues with specific options, will allow to pinpoint specific thing that breaks/fixes things) but rn I would like to focus on adding a tick for opting out of VSM (as that's a performance hog for most I believe). 

I will get back to you in the #21 issue with the trees issue (most likely after adding the VSM switch, unless I get sidetracked lol)

**Comment by CTRQuko** [comment]
Fast travel arround world, if you fly to high the grass an other enviromental props not draw but is normal

https://youtu.be/rZJ6PIyymFs

**Comment by tajemniktv** [comment]
Hey, that's some nice framerate! lol
That popping in looks really annoying, I will see what can be done about this... 

Do you have LOD Dithering enabled in the game video settings? 

I will most likely add a custom slider for foliage view distance as a workaround for now if I don't find a proper fix for that (and if the slider will even work for the popping in lol) 

Anyways, some of these views really are breathtaking. Thanks for that video!<3

**Comment by CTRQuko** [comment]
this settings
![image](https://github.com/user-attachments/assets/f451819e-5789-48dc-8322-9f51b5b1a367)
![image](https://github.com/user-attachments/assets/a1e90d0a-c8a0-4757-8c96-23de669fd3df)

and I use Dlss with the frame generation mod for nvidia.

**Comment by DrShadow34** [comment]
Okay, wanted to do sanity check. Tried disabling mod, set settings to "default" to clear any shenanigans and then set everything to max again, and... Distance foliage still isn't loaded in this particular instance. I guess it maybe something to do with how it works in game (it's on different map square or whatever SF devs called this chunk system thingy). Also, LODs looks kinda similar after I disabled mod, but in some instances it's simply won't load high quality LODs with the mod. 
![with the mod, notice what happens to the ground on the left](https://i.imgur.com/KNJFWZH.jpeg)
![after disabling the mode](https://i.imgur.com/FY2C8jQ.jpeg)
I found one buffer parameter for Nanite that may affect that, gonna try it right now. Weirdly, I indeed don't see how or why mod would affect that. There like, one parameter about Nanite and it shouldn't change how buffers works. But I'm not UE dev (and not programmer at all to begin with), so who knows. Will throw different settings at the wall till something sticks, heh.

**Comment by tajemniktv** [comment]
Maybe it could be a wonky vulkan implementation, have you tried DX12 or is there some specific reason as to why you go with vulk?

**Comment by DrShadow34** [comment]
And sorry, another update. 
Adding this parameters returned my trees where they belong, but looks like I'm backwards evolving in terms of `landscape` part:
![](https://i.imgur.com/ffg9MBJ.jpeg)
```
r.StaticMeshLODDistanceScale=0.1     #Scale factor for the distance used in computing discrete LOD for static meshes.(defaults to 1) (higher values make LODs transition earlier, e.g., 2 is twice as fast / half the distance) 
foliage.LODDistanceScale=4     #Scale factor for the distance used in computing LOD for foliage.
r.SkeletalMeshLODBias=-3    #LOD bias for skeletal meshes - according to wiki. Dunno if that even work
foliage.ForceLOD -1    #If greater than or equal to zero, forces the foliage LOD to that level. (-1 disables foliage LODs?)
r.ViewDistanceScale=5    #Controls the view distance scale. A primitive's MaxDrawDistance is scaled by this value. Higher values will increase view distance but at a performance cost. Default = 1.

landscape.nanite.maxasyncproxybuildspersecond=24    #Number of Async nanite proxies to dispatch per second (should increase nanite load speed, dunno if it really helps) Default = 6.
r.Nanite.CoarseStreamingMeshMemoryPoolSizeInMB 600    #Pool size for streaming in the render mesh & blas data for the coarse nanite meshes (default 200MB) This budget will be part of the mesh streaming pool size.
```

**Comment by DrShadow34** [comment]
> Maybe it could be a wonky vulkan implementation, have you tried DX12 or is there some specific reason as to why you go with vulk?
> 
> edit: answered in edit lol

Well, yeah, wonky fps isn't related to vulkan (other issues may tho). The reason why I'm using it is simple - AMD driver on linux crashing due to some weird vkd3d related issue specifically in this game. And most weird part, that crashing occurs randomly, after 30 minutes and up to 2 hours. It's just annoying. It may be fixed by now, I just got an amdvlk update. Gonna try it.

**Comment by tajemniktv** [comment]
> And sorry, another update.

Don't worry, keep updating us whenever you feel like it. As you can see I spam issues myself with whatever, I'm a bit of a mess myself so gotta keep track of it all lol

**Comment by DrShadow34** [comment]
Okay, final update I think, cause I just gave up at this point. 
I kinda located issue with massive fps drop and found a workaround by simply setting "Foliage Load distance" to default. It also removes some (most) of my changes by shortening foliage draw distance. So yeah, my search for "more trees" was for nothing. 
My shenanigans aside, fps drop if you perform unthinkable and look directly at the ground, still persist. 
![after changing foliage setting I have my fps back](https://i.imgur.com/RaLP42f.jpeg)
![same place, just lower and I look directly on the ground](https://i.imgur.com/CgflhNJ.jpeg)
Notice how GPU now doing nothing. There a small cave nearby, maybe it's amount of objects (like fungus and stuff) that overload engine, cause it need to calculate different math now. That could potentially eat memory bandwidth and cause such issue, while GPU and CPU would pretend to do nothing.  Oh well, small indie company Epic can't be bothered, what you gonna do.

**Comment by tajemniktv** [comment]
I think I found one reason as to why performance is weird. But the answer as to why that is, is even weirder... 

I'm pushing out a build with changes right now, let me know if 1.0.2 gives yall a performance improvment

**Comment by DrShadow34** [comment]
Yep, can confirm significant boost in performance. 
![93fps!](https://i.imgur.com/FPPvOOp.jpeg)
Now looking on the ground is 100 fps, compared to ~50 before. 
![why would it drop frames in the first place? I looked at changed to the config and that made no sense](https://i.imgur.com/PxbPoGZ.jpeg)

Also, I even felt confident enough to get back my beloved trees and it didn't cause that amount of damage now. Alto, it still dropped fps when you look in the distance, yet, that at least make sense and expected to happen. And way better getting half of 100 fps, than half of 60. 
![](https://i.imgur.com/yJtYlg9.jpeg)
