### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by tajemniktv** [tajemniktv/TajsGraph#22]

**Comment by tajemniktv** [comment]
idk honestly, it even happens in the vanilla pretty often, not sure how much I can mitigate this

**Comment by WillScarlettOhara** [comment]
I tested your mod and despite my high end rig (13700k, rtx4070), I'm going to have to disable it. I had no stuttering on vanilla. I also notice a deterioration in LOD changes when I fast travel on the map with hypertube cannons.
What's more, I'd like to be able to control parameters, notably the reflections, which are far too pronounced for my taste on coated concrete which acts as a mirror.

**Comment by tajemniktv** [comment]
Hi, many thanks for the input!
The ability to control specific parameters is planned and is coming soonTM (#8), for now I've mostly added bool settings (yes/no checkboxes), as I'm looking again into all the tweaks the mod is doing. 

The causes for issues with stuttering could be many to be honest, my guess for now is the tweaks I did to garbage collection system (?). Tho I did fine tune it in 2.0 a bit, so it should most likely be better. 

The lod popping in and out is also a wip (#21), but honestly I can't figure this one out at all. I saw similiar behaviour with vanilla (some people also reported that it also happens on vanilla) but it could be that the mod is making it worse/more visible

Again, many thanks for your input:)

**Comment by tajemniktv** [comment]
Oddly for me the game is still stuttering with similar intervals even without the mod, even when standing still. I shall also test without any mods at all I guess. The stuttering doesn't seem to happen in the menu tho. 

I'd need a bigger sample of people if and when the stuttering occurs

**Comment by tajemniktv** [comment]
I can't find any issues with stuttering on latest versions. 

Note: Make sure it's not any other mod causing this and that you don't have too many blueprints on that save.
Closing for now, might be reopened if the issue is either back or someone can factually prove it's caused by TajsGraph
