### ISSUE TITLE
Light cones reset their color when mod is loaded

### ISSUE THREAD

**Issue by Ryder17z** [tajemniktv/TajsGraph#6]
[with mod](https://github.com/user-attachments/assets/f4751f3e-d3ff-40ae-8653-8f9db8ecf1c6)
[without mod](https://github.com/user-attachments/assets/6152881b-8c64-4df4-a572-5ee8955dcf38)

the light presets have not been changed.

**Comment by tajemniktv** [comment]
Hi, thanks for reporting!

Did you make sure to put 
```
r.Shadow.Virtual.Enable 1
```
and
```
r.AOGlobalDistanceField.FastCameraMode 0
```
in your console during this session? That *could* be related to that. 


I will look into that

**Comment by Ryder17z** [comment]
This for whatever reason doesn't happen anymore. The commands do not seem to affect light cones spawned by ceiling lights.

 I don't know what's up with this. My guess is that lights reset due to some other bug. (Lights do not change color until a color is applied by the connected lights panel and it's been glitchy when lights were first introduced.)
